title: Matt Russell
tagline: Test tagline.
email: russellmatt66@gmail.com

description: 'test'

url: 'https://russellmatt66.github.io'
baseurl: ''

collections:
  phys:
    output: true
    permalink: /phys/:title

  compsci:
    output: true
    permalink: /compsci/:title

  math:
    output: true
    permalink: /math/:title

  hpc:
    output: true
    permalink: /hpc/:title

  deeplearning:
    output: true
    permalink: /deeplearning/:title

markdown: kramdown

# Syntax highlighting
highlighter: rouge
# Or this if not on GitHub (?):
# kramdown:
  # input: GFM
  # syntax_highlighter: rouge

sass:
  style: :compressed

gems:
  - jekyll-sitemap
